name: $(date:yyyymmdd)$(rev:.rr) #20191209.00 (what it should look like [with .00 incrementing])

trigger:
  - master

stages:
  - stage: compile
    jobs:
        - job: aspnet
          pool:
            vmImage: ubuntu-18.04
          steps:
            - script: |
                dotnet build 3_devops/Devops.sln